### ISSUE TITLE
Paged container screen type

### ISSUE THREAD

**Issue by NinjaPhenix** [NinjaPhenix/CursedChests#13]
Container screen which is paginated instead of having a scroll bar.

**Comment by angelnc1989** [comment]
I would prefer to just have the chest GUI get bigger with bigger chests like Iron Chests does it.
Scrolling or turning pages is rather annoying.

**Comment by NinjaPhenix** [comment]
Moved to: https://github.com/NinjaPhenix/CursedChests/projects/2
