### ISSUE TITLE
Non-mandatory unsatisfied dependencies

### ISSUE THREAD

**Issue by Napkin** [NinjaPhenix/CursedChests#16]
When launching minecraft I see this:

> [20:32:47] [main/WARN]: Non-mandatory unsatisfied dependencies! 
>  - Mod cursedchests recommends mod {roughlyenoughitems @ [2.8.1.101]}, which is missing!
>  - Mod cursedchests recommends mod {towelette @ [1.5.2]}, which is missing!
> 

While actually

> [20:32:47] [main/INFO]: [FabricLoader] Loading 35 mods: ..., roughlyenoughitems@2.8.2+build.104,...

Thanks for this mod! Cheers!

**Comment by NinjaPhenix** [comment]
Thanks for reporting this I'll update the dependencies to use >= to prevent these from displaying in the future. I'll also remove towelette as its not actually a dependency yet. Version 1.1.15 should be up on curseforge within the next 5 minutes or so.

**Comment by Napkin** [comment]
Sorry, it's still complaining.. seems like "2.8.2+build.104" is smaller than "2.8.2.104". If the check is similar to what Debain does, then "2.8.2+build.104" would be bigger than "2.8.2". It's 2.8.2 since build 104, so I guess that would catch it.

But honestly, it's not really worth an separate update - nor an "issue" actually. Towelette "non-mandatory" dependency is gone :)

Thanks for your work!

**Comment by NinjaPhenix** [comment]
Just found out I defined the version wrong (jar file name uses .104 whereas version in metadata uses +build.104) I'll silently update 1.1.15 on curseforge as to not release a new version number.
