### ISSUE TITLE
Chests don't work with vanilla locking mechanism

### ISSUE THREAD

**Issue by Boundarybreaker** [NinjaPhenix/CursedChests#20]
Vanilla minecraft has a [method for locking containers via NBT](https://minecraft.gamepedia.com/Chest#Container). When a container is locked, you can only open it if you're holding an item with the name of the lock. Cursed chests don't work with vanilla locks.

Steps to reproduce:
1. run the command `/give @p minecraft:chest{BlockEntityTag:{Lock:"Test"}} 1`.
2. run the command `/give @p cursedchests:iron_chest{BlockEntityTag:{Lock:"Test"}} 1`.
3. Place the chests in the world, then with an empty hand, attempt to open each chest.
4. The vanilla chest will refuse to open, but the Cursed Chests chest will open.

**Comment by NinjaPhenix** [comment]
I'll get started on a fix, I planned to have my own kind of locking feature but I guess it wouldn't hurt to let vanilla's also work

**Comment by NinjaPhenix** [comment]
So I think I've got it working, I just dont know how to spawn a key :/ ![Image of Iron Chest Is Locked](https://cdn.discordapp.com/attachments/412105533936500758/585011900782346251/unknown.png)

**Comment by Boundarybreaker** [comment]
Any item named "Test" (or whatever string you put in the lock tag) is a key.

**Comment by NinjaPhenix** [comment]
Oh it works.

**Comment by NinjaPhenix** [comment]
Files processing but it should appear soon (https://minecraft.curseforge.com/projects/cursed-chests/files) If any other changes are needed please make another issue.
