### ISSUE TITLE
Rendering issue on different mod, similar to this one

### ISSUE THREAD

**Issue by encodebow** [NinjaPhenix/CursedChests#26]
Hello,

Firstly I understand this is not your responsibility, and I am fine if you don't want to help. You may know of the Iron-Barrels mod (I've seen you comment on their curse forge saying they can implement the code used in this mod fully into their own instead of depending on it).

They currently have a rendering issue with their mod that causes the barrel contents to not display properly, I have posted the issue here: https://github.com/MarioAndWeegee3/Iron-Barrels/issues/2

However the creator doesn't seem to be active on GitHub (no new commits in last month) and isn't responding to the comments on curse forge.

I've looked through their code & compared it to yours, which it seems to be heavily inspired from, but I can't see what would cause the rendering issue as I'm not familiar with Minecraft Modding. I was hoping with a quick glance you might understand what the issue is, and then either submit a Pull Request to their repo or let me know and I can submit one to try and fix the issue.

Thanks for your time and sorry to trouble you.

**Comment by NinjaPhenix** [comment]
As you said in your most recent comment on Iron Barrels repositry the barrels aren't storing any more than the first 27 slots on inventory, technically the block entity don't even remember what their type is and therefore will never display or drop the full amount of items. I have a patched version if you'd still like to use the mod **you will need to unzip it** though. (github file type limitations)
[ironbarrels-1.2.0+custom.zip](https://github.com/NinjaPhenix/CursedChests/files/3513427/ironbarrels-1.2.0%2Bcustom.zip)

**Comment by NinjaPhenix** [comment]
Version compatable with REI 3.0-pre: 
[ironbarrels-1.2.0+custom.1.zip](https://github.com/NinjaPhenix/CursedChests/files/3513439/ironbarrels-1.2.0%2Bcustom.1.zip)

Will be closing this issue now as it really isn't an issue with CursedChests.
