### ISSUE TITLE
New chest types

### ISSUE THREAD

**Issue by NinjaPhenix** [NinjaPhenix/CursedChests#27]
![](https://cdn.discordapp.com/attachments/594259346897109009/609000231589117952/korikirstu_edh.png)

![](https://cdn.discordapp.com/attachments/594259346897109009/609002109353852932/images.png)

![](https://cdn.discordapp.com/attachments/594259346897109009/609001488030629888/unknown.png)

**Comment by calloatti** [comment]
![image](https://user-images.githubusercontent.com/12817862/62704310-72f50e00-b9c1-11e9-9f3d-adc7f1b863f9.png)

**Comment by NinjaPhenix** [comment]
Moved to: https://github.com/NinjaPhenix/CursedChests/projects/2 feel free to continue to reply with new ideas.
