### ISSUE TITLE
Crash when opening chest in newest version of Fabric/Minecraft.

### ISSUE THREAD

**Issue by krissychan** [NinjaPhenix/CursedChests#5]
https://pastebin.com/3hjn0s3u
Fabric 0.2.7+build.123 (api)
fabric-loader-0.4.1+build.126 pre-release 4 (client/server)

**Comment by NinjaPhenix** [comment]
Thanks for reporting this, Should have it fixed in 2 hours. ( not had access to PC )

**Comment by NinjaPhenix** [comment]
New release on [curseforge](https://minecraft.curseforge.com/projects/cursed-chests/files/2700777) should be compatible with pre-release 3 and 4.
