### ISSUE TITLE
Chest doesn't close until vanilla chest is interacted with

### ISSUE THREAD

**Issue by jessiewestlake** [NinjaPhenix/CursedChests#6]
**Client and Server Mod Ver:** `CursedChests-1.1.8.jar`
**Client and Server Minecraft Ver:** `1.14 Pre-Release 4`

I open the cursed chest, the sound and animation both play. When I leave the chest inventory by pressing `E`, The closing animation plays, but the sound does not. Reopening the cursed chest shows the open animation, but not the sound; the chest then remains open and neither an animation or sound will play at all. The only way to get the cursed chest to close is to open then close a vanilla chest right after trying to close the cursed chest a single time. This triggers the cursed chest to play the closed sound and animation automatically.

**Comment by jessiewestlake** [comment]
Walking a few blocks away from the chest also will make it play the close sound and it can then be properly opened again.

**Comment by NinjaPhenix** [comment]
Just found the cause of this issue and fixed it in commit 04b4eac13abb6c0b56191d4099cd929c0e7b6929 however I'm going to quickly check compatability with Pre-release 3 & 4 before posting it on curseforge.

**Comment by NinjaPhenix** [comment]
Uploaded to curseforge now: [Cursed Chests 1.1.9 pre3 - pre5](https://minecraft.curseforge.com/projects/cursed-chests/files/2702249)
