### ISSUE TITLE
Cursed chest guis don't darken the screen

### ISSUE THREAD

**Issue by Boundarybreaker** [NinjaPhenix/CursedChests#8]
(Cursed chests v1.1.9 according to mod menu)

Whenever you open a cursed chest, its gui doesn't darken the background:

![2019-04-25_20 47 24](https://user-images.githubusercontent.com/6722691/56782311-6d214700-679b-11e9-9d13-27ca538103bb.png)

this results in anything put on the sides of the screen (like REI) that expect to have that darkening there looking weird, and a general feeling of something being "off" even without REI or the like.

**Comment by NinjaPhenix** [comment]
Nice catch, I never actually noticed this at all but its been fixed in [1.1.10](https://minecraft.curseforge.com/projects/cursed-chests/files/2704125)
