### ISSUE TITLE
Confusing recipe

### ISSUE THREAD

**Issue by raphydaphy** [NinjaPhenix/CursedChests#9]
The Iron Chest should be craftable with either a vanilla or a cursed wooden chest.

**Comment by NinjaPhenix** [comment]
I've added a chest -> iron chest recipe in commit 6db7a20bd7e7b6302d4bbe1fa694a1cac05ce3e2 however theres still one issue I'd like to fix before releasing a new version

**Comment by raphydaphy** [comment]
thanks !

**Comment by NinjaPhenix** [comment]
Guess I can close this now...
